export type Language = "en" | "ja";

type Params = Record<string, number | string>;

export const LANGUAGE_STORAGE_KEY = "agmsg-office.lang";
export const SHOW_DATE_STORAGE_KEY = "agmsg-office.show-date";
export const AMBIENT_MOTION_STORAGE_KEY = "agmsg-office.ambient-motion";

export const STRINGS = {
  en: {
    advanced: "Advanced",
    agentsPrefix: "Agents:",
    captionCurrentLine: "Current line",
    captionPlaceholder: "Replay text will appear here.",
    casting: "Casting",
    castingAvatar: "Avatar",
    castingCharacter: "Character",
    castingConfigJson: "Current config JSON",
    castingDevOnlyNotice:
      "Character upload is available only when agmsg Office is running with npm run dev. Existing custom characters still appear here.",
    castingFallback: "fallback",
    castingOverride: "override",
    castingRename: "Display name",
    castingRenameHint:
      "When empty, the speaking agent name (Boss for host) is shown.",
    castingReplaceCharacter: "Replace character",
    castingResetAll: "Reset all to default",
    castingResetRow: "Reset to default",
    castingStageDisplay: "Stage label",
    castingStorageNotice:
      "Casting and rename settings are stored in localStorage key {key}.",
    castingTargetSlot: "Target slot: {slot}",
    characterMotion: "Characters move around",
    characterName: "Character name",
    choose: "Choose",
    close: "Close",
    controlDespawn: "{agent} left the session.",
    controlGeneric: "A system event came through: {command}.",
    cancel: "Cancel",
    delete: "Delete",
    errorImportInvalidJson:
      "Import failed. The selected file is not valid JSON.",
    errorImportInvalidRecord:
      "Import failed. Record {index} must include id, team, from_agent, to_agent, body, created_at, and optional read_at.",
    errorImportNotArray: "Import failed. The JSON file must contain an array.",
    errorImportRead:
      "Import failed. Choose a JSON file containing agmsg message records.",
    errorLoadAgmsgHistory: "Failed to load agmsg history for {team}.",
    errorLoadAssets: "Failed to load assets.json",
    errorLoadCharacters: "Failed to load character assets",
    errorLoadSample: "Failed to load sample agmsg log",
    errorLocalApi: "Local agmsg API is not available.",
    errorLocalUnavailable: "Local agmsg data is unavailable.",
    errorNoTeams: "No agmsg teams were found. Using sample log.",
    errorUsingSample: "Using sample log: {reason}",
    hide: "Hide",
    importedFileFallback: "imported file",
    importJson: "Import JSON",
    language: "Language",
    logListLabel: "agmsg entries",
    myCharacters: "My characters",
    myCharactersEmpty: "No uploaded characters yet.",
    teamFallback: "this team",
    logHeadingImport: "imported file",
    logHeadingSample: "agmsg sample",
    metaSystem: "System",
    narrationIntro: "Welcome to {team}! Replaying {count} messages.",
    narrationOutro: "That is the end of the log. Thanks for watching!",
    playback: "Playback",
    reloadCurrentTeam: "Reload current team",
    save: "Save",
    saving: "Saving...",
    show: "Show",
    showDate: "Show timestamp",
    source: "Source",
    sourceImportedStatus: "Imported file: {name} ({count} entries)",
    sourceLiveStatus: "Live agmsg: {team} ({count} entries)",
    sourceLoading: "Loading log...",
    sourceSampleOption: "Sample",
    sourceSampleStatus: "Sample log ({count} entries)",
    speed: "Speed",
    spritesheetPreview: "Spritesheet idle preview",
    spritesheetSkillHint:
      "Use a spritesheet.webp generated by the agmsg-character-sprites skill.",
    spritesheetUpload: "Upload spritesheet.webp",
    start: "Start",
    stop: "Stop",
    pause: "Pause",
    systemNotePrefix: "System note:",
    stageLabel: "Agent stage",
    theater: "Theater",
    theaterExit: "Exit theater",
    topbarSubtitle: "Replay agent messages as a character stage.",
    unknown: "unknown",
    uploadNewCharacter: "Upload new",
    portraitUpload: "Optional portrait.png",
  },
  ja: {
    advanced: "詳細",
    agentsPrefix: "エージェント:",
    captionCurrentLine: "現在の行",
    captionPlaceholder: "再生テキストがここに表示されます。",
    casting: "配役",
    castingAvatar: "アバター",
    castingCharacter: "キャラクター",
    castingConfigJson: "現在の設定JSON",
    castingDevOnlyNotice:
      "キャラのアップロードは npm run dev で agmsg Office を起動しているときだけ使えます。登録済みのカスタムキャラ表示は利用できます。",
    castingFallback: "フォールバック中",
    castingOverride: "上書き中",
    castingRename: "表示名",
    castingRenameHint:
      "未設定のときは発言エージェント名（host は Boss）が表示されます。",
    castingReplaceCharacter: "キャラを差し替え",
    castingResetAll: "全てデフォルトに戻す",
    castingResetRow: "デフォルトに戻す",
    castingStageDisplay: "ステージ表示",
    castingStorageNotice:
      "配役と改名は localStorage キー {key} に保存されます。",
    castingTargetSlot: "対象スロット: {slot}",
    characterMotion: "キャラクターを動かす",
    characterName: "キャラ名",
    choose: "選択",
    close: "閉じる",
    controlDespawn: "{agent} がセッションから退出しました。",
    controlGeneric: "システムイベントを受信しました: {command}。",
    cancel: "キャンセル",
    delete: "削除",
    errorImportInvalidJson:
      "インポートに失敗しました。選択したファイルは有効な JSON ではありません。",
    errorImportInvalidRecord:
      "インポートに失敗しました。{index} 件目には id、team、from_agent、to_agent、body、created_at、および任意の read_at が必要です。",
    errorImportNotArray:
      "インポートに失敗しました。JSON ファイルは配列である必要があります。",
    errorImportRead:
      "インポートに失敗しました。agmsg メッセージレコードを含む JSON ファイルを選択してください。",
    errorLoadAgmsgHistory: "{team} の agmsg 履歴を読み込めませんでした。",
    errorLoadAssets: "assets.json を読み込めませんでした",
    errorLoadCharacters: "キャラクターアセットを読み込めませんでした",
    errorLoadSample: "サンプル agmsg ログを読み込めませんでした",
    errorLocalApi: "ローカル agmsg API を利用できません。",
    errorLocalUnavailable: "ローカル agmsg データを利用できません。",
    errorNoTeams: "agmsg チームが見つかりません。サンプルログを使用します。",
    errorUsingSample: "サンプルログを使用中: {reason}",
    hide: "非表示",
    importedFileFallback: "インポートしたファイル",
    importJson: "JSON をインポート",
    language: "言語",
    logListLabel: "agmsg エントリ",
    myCharacters: "マイキャラ",
    myCharactersEmpty: "アップロード済みのキャラはまだありません。",
    teamFallback: "このチーム",
    logHeadingImport: "インポートしたファイル",
    logHeadingSample: "agmsg サンプル",
    metaSystem: "システム",
    narrationIntro: "{team} へようこそ。{count} 件のメッセージを再生します。",
    narrationOutro: "ログの最後です。ご覧いただきありがとうございました。",
    playback: "再生",
    reloadCurrentTeam: "現在のチームを再読み込み",
    save: "保存",
    saving: "保存中...",
    show: "表示",
    showDate: "日時を表示",
    source: "ソース",
    sourceImportedStatus: "インポート: {name} ({count} 件)",
    sourceLiveStatus: "Live agmsg: {team} ({count} 件)",
    sourceLoading: "ログを読み込み中...",
    sourceSampleOption: "サンプル",
    sourceSampleStatus: "サンプルログ ({count} 件)",
    speed: "速度",
    spritesheetPreview: "スプライトの idle プレビュー",
    spritesheetSkillHint:
      "agmsg-character-sprites スキルで生成した spritesheet.webp を使ってください。",
    spritesheetUpload: "spritesheet.webp をアップロード",
    start: "開始",
    stop: "停止",
    pause: "一時停止",
    systemNotePrefix: "システムメモ:",
    stageLabel: "エージェントステージ",
    theater: "シアター",
    theaterExit: "シアター解除",
    topbarSubtitle:
      "エージェントのメッセージをキャラクターステージとして再生します。",
    unknown: "不明",
    uploadNewCharacter: "新規アップロード",
    portraitUpload: "portrait.png をアップロード（任意）",
  },
} as const;

export type I18nKey = keyof typeof STRINGS.en;

export function detectLanguage(): Language {
  const storedLanguage = readStoredLanguage();
  if (storedLanguage) return storedLanguage;

  if (
    typeof navigator !== "undefined" &&
    navigator.language.toLowerCase().startsWith("ja")
  ) {
    return "ja";
  }
  return "en";
}

export function saveLanguage(language: Language) {
  try {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  } catch {
    // Ignore storage failures; the in-memory choice still applies.
  }
}

export function detectShowDate(): boolean {
  try {
    const value = localStorage.getItem(SHOW_DATE_STORAGE_KEY);
    if (value === "false") return false;
    if (value === "true") return true;
  } catch {
    return true;
  }
  return true;
}

export function saveShowDate(showDate: boolean) {
  try {
    localStorage.setItem(SHOW_DATE_STORAGE_KEY, String(showDate));
  } catch {
    // Ignore storage failures; the in-memory choice still applies.
  }
}

export function detectAmbientMotion(): boolean {
  try {
    const value = localStorage.getItem(AMBIENT_MOTION_STORAGE_KEY);
    if (value === "false") return false;
    if (value === "true") return true;
  } catch {
    return true;
  }
  return true;
}

export function saveAmbientMotion(ambientMotion: boolean) {
  try {
    localStorage.setItem(AMBIENT_MOTION_STORAGE_KEY, String(ambientMotion));
  } catch {
    // Ignore storage failures; the in-memory choice still applies.
  }
}

export function t(
  language: Language,
  key: I18nKey,
  params: Params = {},
): string {
  let value: string = STRINGS[language][key];
  for (const [name, replacement] of Object.entries(params)) {
    value = value.replaceAll(`{${name}}`, String(replacement));
  }
  return value;
}

function readStoredLanguage(): Language | undefined {
  try {
    const value = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return value === "en" || value === "ja" ? value : undefined;
  } catch {
    return undefined;
  }
}
